# Generated by Django 4.1.4 on 2023-01-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_chead1_blogpost_chead2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='subcategory',
        ),
    ]
